### ISSUE TITLE
Moindre carré non fonctionnel

### ISSUE THREAD

**Issue by ldgaulin** [Patrih/S5P1#2]
Grosse erreur autour du 0 ; pour isoler les paramètres on doit isoler `-1/Fsk` et `Fsk` est trop proche de zéro, ce qui cause un bruit trop grand et une approximation passant par 0 (causant un infini dans l'approximation).

Le problème se trouve à la ligne 31 de ce [fichier](https://github.com/Patrih/S5P1/blob/dev/MatLab/IDENTIFICATION_MC.m#L31).

**Comment by ldgaulin** [comment]
La solution proposée est de rajouter un offset. TODO

**Comment by louis-etne** [comment]
Done, effectivement ça fonctionne. Voir 9f4b11c60112f5f7fa5e3514ba4863b821acc531.
